# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft / Forge
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.0
forge_version_range=[47,)
loader_version_range=[47,)

# Mappings (Parchment = parametre isimleri dahil tam harita)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

# Mod Bilgileri
mod_id=axiom
mod_name=Axiom
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.axiom
mod_authors=Archon
mod_description=No reason. No origin. Just power.