modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="axiom"
version="${file.jarVersion}"
displayName="Axiom"
authors="Archon"
description='''
No reason. No origin. Just power.
'''

[[dependencies.axiom]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.axiom]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"